In [1]:
using Enzyme

function velocity!(u, x, mu)
    
    for i in 1:3
        u[i] = mu * (x[i] * x[i])
    end
    nothing
end

x = [0.653484990079922, 0.744572635699587, 0.23483535966444968]

3-element Vector{Float64}:
 0.653484990079922
 0.744572635699587
 0.23483535966444968

In [2]:
u = zeros(3)
deltaU = zeros(3,3)
mu = 2
for i in 1:3
    dx = zeros(3)
    du = zeros(3)
    du[i] = 1
    Enzyme.autodiff(velocity!, Const, Duplicated(u, du), Duplicated(x, dx), Const(mu))
    deltaU[i,:] = dx
end

In [3]:
deltaU

3×3 Matrix{Float64}:
 2.61394  0.0      0.0
 0.0      2.97829  0.0
 0.0      0.0      0.939341

In [4]:
u

3-element Vector{Float64}:
 0.8540852645195115
 1.1087768196652596
 0.11029529229746288