In [17]:
using Enzyme

function vecadd!(c, a, b)
    c .= a .+ b
    nothing
end


vecadd! (generic function with 1 method)

In [26]:
n = 5
a = rand(n); b = rand(n); c = zeros(n)
vecadd!(c, a, b)
c

5-element Vector{Float64}:
 0.9486988091206554
 0.8049091128779879
 1.7398583408296016
 1.0925251036271484
 0.5120472446401827

In [27]:
da = zero(a); db = zero(b); dc = fill!(similar(c), 1)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [28]:
autodiff(vecadd!, Const, Duplicated(c, dc), Duplicated(a, da), Duplicated(b, db))

()

In [29]:
da

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [30]:
dc

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [31]:
db

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0